import { useMemo, useState } from "react";
import { cn } from "../utils/cn";

// ─── Weapon data (CS 1.6 buy menu) ───
type Weapon = {
  id: string;
  name: string;
  slot: "primary" | "secondary" | "equipment";
  price: number;
  bind: string;
};

const WEAPONS: Weapon[] = [
  // Primary
  { id: "ak47", name: "AK-47", slot: "primary", price: 2500, bind: "ak47" },
  { id: "m4a1", name: "M4A1", slot: "primary", price: 3100, bind: "m4a1" },
  { id: "awp", name: "AWP", slot: "primary", price: 4750, bind: "awp" },
  { id: "scout", name: "Scout", slot: "primary", price: 2750, bind: "scout" },
  { id: "famas", name: "FAMAS", slot: "primary", price: 2250, bind: "famas" },
  { id: "galil", name: "Galil", slot: "primary", price: 2000, bind: "galil" },
  { id: "aug", name: "AUG", slot: "primary", price: 3500, bind: "aug" },
  { id: "sg552", name: "SG-552", slot: "primary", price: 3500, bind: "sg552" },
  { id: "mp5", name: "MP5 Navy", slot: "primary", price: 1500, bind: "mp5" },
  { id: "tmp", name: "TMP", slot: "primary", price: 1250, bind: "tmp" },
  { id: "m3", name: "M3", slot: "primary", price: 1700, bind: "m3" },
  { id: "xm1014", name: "XM1014", slot: "primary", price: 3000, bind: "xm1014" },
  // Secondary
  { id: "deagle", name: "Desert Eagle", slot: "secondary", price: 650, bind: "deagle" },
  { id: "usp", name: "USP", slot: "secondary", price: 500, bind: "usp" },
  { id: "glock", name: "Glock 18", slot: "secondary", price: 400, bind: "glock" },
  { id: "p228", name: "P228", slot: "secondary", price: 600, bind: "p228" },
  { id: "elite", name: "Dual Elites", slot: "secondary", price: 800, bind: "elite" },
  { id: "fiveseven", name: "Five-Seven", slot: "secondary", price: 750, bind: "fiveseven" },
  // Equipment
  { id: "vest", name: "Kevlar", slot: "equipment", price: 650, bind: "vest" },
  { id: "vesthelm", name: "Kevlar+Helm", slot: "equipment", price: 1000, bind: "vesthelm" },
  { id: "defuser", name: "Defuse Kit", slot: "equipment", price: 200, bind: "defuser" },
  { id: "flash", name: "Flashbang", slot: "equipment", price: 200, bind: "flash" },
  { id: "hegren", name: "HE Grenade", slot: "equipment", price: 300, bind: "hegren" },
  { id: "smoke", name: "Smoke", slot: "equipment", price: 300, bind: "sgren" },
  { id: "primammo", name: "Primary Ammo", slot: "equipment", price: 60, bind: "primammo" },
  { id: "secammo", name: "Pistol Ammo", slot: "equipment", price: 25, bind: "secammo" },
];

const CT_WEAPONS = ["m4a1", "aug", "famas", "galil", "mp5", "tmp", "m3", "xm1014", "scout", "awp", "deagle", "usp", "p228", "elite", "fiveseven", "vest", "vesthelm", "defuser", "flash", "hegren", "smoke", "primammo", "secammo"];
const T_WEAPONS = ["ak47", "sg552", "famas", "galil", "mp5", "tmp", "m3", "xm1014", "scout", "awp", "deagle", "glock", "p228", "elite", "fiveseven", "vest", "vesthelm", "flash", "hegren", "smoke", "primammo", "secammo"];

const KEYS = [
  "F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12",
  "KP_END","KP_DOWNARROW","KP_PGDN","KP_LEFTARROW","KP_5","KP_RIGHTARROW",
  "KP_HOME","KP_UPARROW","KP_PGUP","KP_INS","KP_DEL","KP_ENTER",
  "MOUSE3","MOUSE4","MOUSE5","MWHEELUP","MWHEELDOWN",
  "CAPSLOCK","SHIFT","CTRL","ALT","B","V","C","X","Z","O","P","H","T","G",
];

const PRESET_COMBOS = [
  { name: "Full ECO", items: "vest;deagle;secammo", desc: "Pistol round upgrade" },
  { name: "Full BUY CT", items: "vesthelm;flash;flash;hegren;sgren;m4a1;primammo;deagle;secammo;defuser", desc: "M4 full load" },
  { name: "Full BUY T", items: "vesthelm;flash;flash;hegren;sgren;ak47;primammo;deagle;secammo", desc: "AK full load" },
  { name: "AWP Load", items: "vesthelm;awp;primammo;deagle;secammo;flash;hegren", desc: "Sniper kit" },
  { name: "Force Buy", items: "vest;famas;galil;primammo;flash", desc: "Low money rush" },
  { name: "Nade Set", items: "flash;flash;hegren;sgren", desc: "Utility only" },
];

export default function BindsBuilder() {
  const [team, setTeam] = useState<"CT" | "T">("CT");
  const [binds, setBinds] = useState<Record<string, string>>({});
  const [editingKey, setEditingKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const teamWeapons = useMemo(() => {
    const ids = team === "CT" ? CT_WEAPONS : T_WEAPONS;
    return WEAPONS.filter((w) => ids.includes(w.id));
  }, [team]);

  const teamTotal = useMemo(() => {
    let total = 0;
    for (const key in binds) {
      if (!binds[key]) continue;
      for (const part of binds[key].split(";")) {
        const bind = part.trim();
        const weapon = WEAPONS.find((w) => w.bind === bind);
        if (weapon) total += weapon.price;
      }
    }
    return total;
  }, [binds]);

  const generateScript = () => {
    let script = "// MOHICAN buyscript.cfg — generated by cfg.mohican.xyz\n";
    script += `// Team: ${team} · ${Object.keys(binds).length} binds · $${teamTotal} total\n\n`;
    for (const key in binds) {
      if (!binds[key]) continue;
      script += `bind "${key}" "${binds[key]}"\n`;
    }
    script += '\n// quick-buy from anywhere\nalias "buy_full" "buy"\n';
    return script;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateScript());
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="grid lg:grid-cols-[1fr_320px] gap-4">
      {/* Left: binds editor */}
      <div className="bg-zinc-900/40 border border-zinc-800 rounded-lg p-4">
        {/* team toggle */}
        <div className="flex gap-1 mb-4">
          {(["CT", "T"] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTeam(t)}
              className={cn(
                "px-4 py-2 rounded text-sm font-mono border transition-all",
                team === t
                  ? t === "CT"
                    ? "bg-sky-500/15 border-sky-500/50 text-sky-300"
                    : "bg-amber-500/15 border-amber-500/50 text-amber-300"
                  : "border-zinc-700 text-zinc-500 hover:text-zinc-300"
              )}
            >
              {t === "CT" ? "🔵 Counter-Terrorist" : "🟡 Terrorist"}
            </button>
          ))}
          <div className="flex-1" />
          <button
            onClick={handleCopy}
            className={cn(
              "px-4 py-2 rounded border text-sm font-mono transition-all",
              copied
                ? "border-emerald-500 text-emerald-300 bg-emerald-500/10"
                : "border-orange-500/50 text-orange-300 hover:bg-orange-500/10"
            )}
          >
            {copied ? "✓ COPIED" : "↓ COPY BUYSCRIPT"}
          </button>
        </div>

        {/* key grid */}
        <p className="text-xs font-mono text-zinc-500 mb-2">
          Click a key → add weapons to it
        </p>
        <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-7 xl:grid-cols-8 gap-1.5 mb-3">
          {KEYS.map((k) => (
            <button
              key={k}
              onClick={() => setEditingKey(editingKey === k ? null : k)}
              className={cn(
                "px-1.5 py-2 rounded border text-[10px] font-mono transition-all",
                editingKey === k
                  ? "border-orange-500 bg-orange-500/15 text-orange-200"
                  : binds[k]
                  ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300"
                  : "border-zinc-700 text-zinc-400 hover:border-zinc-500 hover:text-zinc-200"
              )}
              title={binds[k] || "empty"}
            >
              {k}
            </button>
          ))}
        </div>

        {/* weapon selection */}
        {editingKey ? (
          <div className="border-t border-zinc-800 pt-3">
            <p className="text-xs font-mono text-zinc-400 mb-2">
              Editing: <span className="text-orange-300">{editingKey}</span>
            </p>
            <div className="flex gap-1.5 flex-wrap mb-3">
              {PRESET_COMBOS.map((pc) => (
                <button
                  key={pc.name}
                  onClick={() => setBinds((prev) => ({ ...prev, [editingKey]: pc.items }))}
                  title={pc.desc}
                  className="px-2.5 py-1.5 rounded border border-violet-500/40 hover:border-violet-400 bg-violet-500/5 hover:bg-violet-500/15 text-[10px] font-mono text-violet-300 transition-colors"
                >
                  {pc.name}
                </button>
              ))}
              <button
                onClick={() => setBinds((prev) => ({ ...prev, [editingKey]: "" }))}
                className="px-2.5 py-1.5 rounded border border-zinc-700 hover:border-red-500/50 text-[10px] font-mono text-zinc-500 hover:text-red-300 transition-colors"
              >
                clear
              </button>
            </div>
            <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-4 xl:grid-cols-5 gap-1.5 max-h-64 overflow-y-auto pr-1">
              {teamWeapons.map((w) => (
                <button
                  key={w.id}
                  onClick={() => {
                    const cur = binds[editingKey] || "";
                    const next = cur ? `${cur};${w.bind}` : w.bind;
                    setBinds((prev) => ({ ...prev, [editingKey]: next }));
                  }}
                  className="px-2 py-1.5 rounded border border-zinc-700 hover:border-orange-500/50 bg-zinc-900/50 text-[10px] font-mono text-zinc-300 hover:text-amber-100 transition-all text-left"
                >
                  <span className="block truncate">{w.name}</span>
                  <span className="block text-zinc-600 text-[9px]">${w.price}</span>
                </button>
              ))}
            </div>
          </div>
        ) : (
          <p className="text-[10px] font-mono text-zinc-600 italic">
            Select a key above to build a buy bind for it
          </p>
        )}
      </div>

      {/* Right: current binds */}
      <div className="bg-zinc-900/40 border border-zinc-800 rounded-lg p-4">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-mono text-zinc-400">Active binds</p>
          <span className="text-[10px] font-mono text-emerald-400">${teamTotal}</span>
        </div>
        <div className="space-y-1 max-h-[420px] overflow-y-auto pr-1">
          {Object.keys(binds).length === 0 ? (
            <p className="text-[10px] font-mono text-zinc-600 italic">
              No binds yet — click a key
            </p>
          ) : (
            Object.entries(binds)
              .filter(([, v]) => v)
              .map(([key, val]) => (
                <div key={key} className="flex items-center gap-2 py-1 px-2 rounded bg-zinc-900/60 border border-zinc-800">
                  <span className="text-[10px] font-mono text-orange-300 w-20 flex-shrink-0">
                    {key}
                  </span>
                  <span className="text-[10px] font-mono text-zinc-400 truncate flex-1">
                    {val}
                  </span>
                  <button
                    onClick={() => setBinds((prev) => ({ ...prev, [key]: "" }))}
                    className="text-zinc-600 hover:text-red-400 text-xs flex-shrink-0"
                  >
                    ✕
                  </button>
                </div>
              ))
          )}
        </div>
      </div>
    </div>
  );
}
